export const UserData = [
    {
        id:1,
        year: 2017,
        quizcompleted: 12,
        surveycompleted: 23,
        anscorrect: 32,
        answrong:23,
    },
    {
        id:2,
        year: 2018,
        quizcompleted: 34,
        surveycompleted: 43,
        anscorrect: 123,
        answrong:32,
    },
    {
        id:3,
        year: 2019,
        quizcompleted: 123,
        surveycompleted: 35,
        anscorrect: 112,
        answrong:34,
    },
    {
        id:4,
        year: 2020,
        quizcompleted: 23,
        surveycompleted: 2,
        anscorrect: 21,
        answrong:3,
    },
    {
        id:5,
        year: 2021,
        quizcompleted: 63,
        surveycompleted: 74,
        anscorrect: 234,
        answrong:65,
    },
    {
        id:6,
        year: 2022,
        quizcompleted: 231,
        surveycompleted: 123,
        anscorrect: 1234,
        answrong:231,
    },
    {
        id:7,
        year: 2023,
        quizcompleted: 232,
        surveycompleted: 56,
        anscorrect: 987,
        answrong:56,
    },
    {
        id:8,
        year: 2024,
        quizcompleted: 123,
        surveycompleted: 435,
        anscorrect: 1234,
        answrong:345,
    },
]